sonar.projectKey=com.walmart.gtp-shared-components
sonar.projectName=GTP-Shared-Components
sonar.projectVersion=1.0.0
sonar.host.url=http://sonar.looper.prod.walmartlabs.com

sonar.sources=src/next
sonar.tests=src/next
sonar.sourceEncoding=UTF-8

#Exclusions property
sonar.exclusions=**/node_modules/**, **/__tests__/**, **/*test.tsx, **/*test.ts
sonar.test.inclusions=src/next/components/__tests__/**, **/*test.tsx
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-report.xml
