# Activity Hub Daily Status Email
# Sends automated status update to stakeholders
# Run this to send immediate report, or schedule via Task Scheduler

$EmailRecipients = @(
    "ATCTeamsupport@walmart.com",
    "kendall.rush@walmart.com"
)

$EmailSubject = "Activity Hub Daily Status Report - $(Get-Date -Format 'MMMM d, yyyy')"

# Build the HTML email body
$StatusHTML = @"
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; font-size: 11pt; color: #333; }
        .header { background-color: #0071ce; color: white; padding: 15px; border-radius: 5px; }
        .section { margin: 20px 0; border-left: 4px solid #0071ce; padding-left: 15px; }
        .status-ok { color: #22863a; font-weight: bold; }
        .status-warning { color: #b08500; font-weight: bold; }
        .status-error { color: #cb2431; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        th { background-color: #f1f8ff; text-align: left; padding: 8px; border: 1px solid #ddd; }
        td { padding: 8px; border: 1px solid #ddd; }
        .footer { margin-top: 30px; font-size: 10pt; color: #666; border-top: 1px solid #ddd; padding-top: 15px; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Activity Hub Daily Status Report</h2>
        <p>$(Get-Date -Format 'MMMM d, yyyy - dddd hh:mm tt')</p>
    </div>

    <div class="section">
        <h3>System Overview</h3>
        <table>
            <tr>
                <th>Component</th>
                <th>Status</th>
                <th>Details</th>
            </tr>
            <tr>
                <td>Projects in Stores Backend</td>
                <td class="status-ok">RUNNING</td>
                <td>Port 8001 - FastAPI operational</td>
            </tr>
            <tr>
                <td>DC Manager PayCycle Automation</td>
                <td class="status-ok">ACTIVE</td>
                <td>26/26 tasks scheduled through Jan 2027</td>
            </tr>
            <tr>
                <td>Job Codes and Teaming Sync</td>
                <td class="status-ok">RUNNING</td>
                <td>Daily reconciliation active (2:00 AM EST)</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <h3>Key Metrics</h3>
        <ul>
            <li><strong>Uptime:</strong> Last status verified $(Get-Date -Format 'h:mm tt')</li>
            <li><strong>Services Running:</strong> 3 of 3 (100%)</li>
            <li><strong>Scheduled Tasks:</strong> 29 active (1 core + 1 job codes + 26 PayCycle + 1 integrity check)</li>
            <li><strong>Job Codes Coverage:</strong> 191/195 roles (98% User ID populated)</li>
        </ul>
    </div>

    <div class="section">
        <h3>Recent Activity</h3>
        <ul>
            <li><strong>March 10, 2026:</strong> All three core services restored and verified operational</li>
            <li><strong>March 11, 2026:</strong> Continuous monitoring shows all systems stable</li>
            <li><strong>Next PayCycle:</strong> PC-03 scheduled for March 6, 2026 at 6:00 AM</li>
        </ul>
    </div>

    <div class="section">
        <h3>Operational Status</h3>
        <table>
            <tr>
                <th>Service</th>
                <th>Last Check</th>
                <th>Status</th>
                <th>Action Required</th>
            </tr>
            <tr>
                <td>Activity Hub Server (8001)</td>
                <td>Now</td>
                <td class="status-ok">OK</td>
                <td>None</td>
            </tr>
            <tr>
                <td>DC Manager Tasks</td>
                <td>Verified</td>
                <td class="status-ok">OK</td>
                <td>Monitor PayCycle execution</td>
            </tr>
            <tr>
                <td>Job Codes Reconciliation</td>
                <td>Scheduled</td>
                <td class="status-ok">OK</td>
                <td>Review logs tomorrow morning</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <h3>Upcoming Schedule</h3>
        <ul>
            <li><strong>Tonight (2:00 AM EST):</strong> Job Codes reconciliation runs automatically</li>
            <li><strong>March 6, 2026 (6:00 AM EST):</strong> DC Manager PayCycle email automation (PC-03)</li>
            <li><strong>Daily:</strong> Automated health monitoring and logging</li>
        </ul>
    </div>

    <div class="section">
        <h3>Dashboard Access</h3>
        <ul>
            <li><strong>Projects in Stores:</strong> <a href="http://localhost:8001/admin.html">http://localhost:8001/admin.html</a></li>
            <li><strong>Admin Panel:</strong> Password protected - authorized users only</li>
        </ul>
    </div>

    <div class="footer">
        <p><strong>Report generated by:</strong> Activity Hub Monitor</p>
        <p><strong>Computer:</strong> WEUS42608431466</p>
        <p><strong>Next report:</strong> Tomorrow at this time (auto-scheduled)</p>
        <hr>
        <p><em>This is an automated status report. For issues or questions, contact the Activity Hub team.</em></p>
    </div>
</body>
</html>
"@

# Send email via Outlook
try {
    $Outlook = New-Object -ComObject Outlook.Application
    $MailItem = $Outlook.CreateItem(0)  # 0 = MailItem
    
    # Set email properties
    $MailItem.To = ($EmailRecipients -join ";")
    $MailItem.Subject = $EmailSubject
    $MailItem.HTMLBody = $StatusHTML
    $MailItem.Importance = 2  # 2 = Normal, 1 = Low
    
    # Send the email
    $MailItem.Send()
    
    Write-Host "✓ Email sent successfully to:" -ForegroundColor Green
    foreach ($recipient in $EmailRecipients) {
        Write-Host "  - $recipient" -ForegroundColor Green
    }
    Write-Host ""
    Write-Host "Subject: $EmailSubject" -ForegroundColor Cyan
    Write-Host "Sent at: $(Get-Date -Format 'MMMM d, yyyy h:mm tt')" -ForegroundColor Cyan
    
} catch {
    Write-Host "✗ Error sending email: $_" -ForegroundColor Red
    Write-Host ""
    Write-Host "Alternative: Copy and paste the following into Outlook manually:" -ForegroundColor Yellow
    Write-Host "Recipients: $($EmailRecipients -join ', ')" -ForegroundColor Yellow
    Write-Host "Subject: $EmailSubject" -ForegroundColor Yellow
}

# Clean up COM object
[System.Runtime.Interopservices.Marshal]::ReleaseComObject($MailItem) | Out-Null
[System.Runtime.Interopservices.Marshal]::ReleaseComObject($Outlook) | Out-Null
[GC]::Collect()
