/* eslint-env node */
const camelCase = require('lodash/camelCase');
const map = require('lodash/map');
// const path = require('path');
const startCase = require('lodash/startCase');

const pascalCase = (str) => {
  const out = camelCase(str);
  return out[0].toUpperCase() + out.slice(1);
};

/**
 * Icon markdown file template
 */
const iconMarkdownTemplate = (className, images) => `\`\`\`js
// Automatically generated by refreshIcons.
import {Icons} from '@walmart/gtp-shared-icons';

<IconWrapper caption>
${images
  .map((i) => {
    const sz = i.get('size');
    if (sz === '16') {
      return `  <Icons.${className} size={${i.get('size')}} />
  <Icons.${className} size="small" />`;
    } else if (sz === '24') {
      return `  <Icons.${className} size={${i.get('size')}} />
  <Icons.${className} size="medium" />`;
    } else if (sz === '32') {
      return `  <Icons.${className} size={${i.get('size')}} />
  <Icons.${className} size="large" />`;
    } else {
      return `  <Icons.${className} size={${sz}} />`;
    }
  })
  .join('\n')}
</IconWrapper>;
\`\`\`
`;

/**
 * Icon tsx file template
 */
const iconTemplate = (className, images, componentRelativePath) => {
  const getImportName = (size) => camelCase(`${className}-${size}`);
  const imports = [];
  const sizes = new Set();
  const sources = new Map();
  const validProps = [];

  images.forEach((i) => {
    const size = i.get('size');
    imports.push(
      `import ${getImportName(size)} from '${i.get('importPath')}';`,
    );
    sizes.add(size);
    sources.set(size, getImportName(size));
    if (size === '16') {
      sources.set('small', getImportName(size));
    } else if (size === '24') {
      sources.set('medium', getImportName(size));
    } else if (size === '32') {
      sources.set('large', getImportName(size));
    }
    validProps.push({size});
  });

  const imageStyle = 'styles(iconSizes[`${size}`], color).image';
  const imageSource = 'sources[`${size}`]';

  return `// Automatically generated by refreshIcons.
import * as React from 'react';
import {
  Image,
  ImageProps,
  ImageStyle,
  StyleProp,
  StyleSheet
} from 'react-native';
import {a11yRole} from '../utils/utils';
import {iconSizes, IconSize} from '../utils/types';

/* Source Files */
${imports.join('\n')}

const sources = {
${Array.from(sources.entries())
  .map(([key, importName]) => `  '${key}': ${importName},`)
  .join('\n')}
};

export type ${className}Props = Omit<ImageProps, 'source' | 'style'> & {
  /**
   * Icon color
   * @default black
   */
  color?: string;
  /**
   * Icon size
   * Valid values: ${Array.from(sizes.values())
     .map((s) => {
       if (s === '16') {
         return `${s} | small`;
       } else if (s === '24') {
         return `${s} | medium`;
       } else if (s === '32') {
         return `${s} | large`;
       } else {
         return `${s}`;
       }
     })
     .join(' | ')};
   * @default 16
   */
  size?: IconSize ${Array.from(sizes.values())
    .map((s) => {
      if (!['16', '24', '32'].includes(s)) {
        return `| ${s}`;
      }
    })
    .join('')};
  /**
   * If provided, the <strong>style</strong> to provide to the container.
   * This property is prefixed with <strong>UNSAFE</strong> as its use
   * often results in <strong>unintended side effects</strong>.
   */
  UNSAFE_style?: StyleProp<ImageStyle>;
};

/**
 * ${startCase(className)}.
 *
 * \`\`\`js
 * import {Icons} from '@walmart/gtp-shared-icons';
 * <Icons.${className} />
 * \`\`\`
 */
const ${className}: React.FC<${className}Props> = (
  props: ${className}Props,
) => {
  const {color = 'black', size = 16, UNSAFE_style = {}, ...rest} = props;
  return (
    <Image
      accessibilityRole={a11yRole('image')}
      testID={${className}.displayName!}
      source={${imageSource}}
      style={[${imageStyle}, UNSAFE_style]}
      {...rest}
    />
  );
};

const styles = (size: number, color: string) =>
  StyleSheet.create({
    image: {
      height: size,
      width: size,
      tintColor: color,
    },
  });

${className}.displayName = '${className}';
export {${className}};
`;
};

/**
 * Icon index template
 */
const iconIndexTemplate = (icons) => {
  const warning = '// Automatically generated by refreshIcons.\n';
  const deprecatedSection =
    '// DEPRECATED: these are no longer in the LD repo.\n' +
    "export * from './deprecated';\n";

  const exportSection = `${map(
    icons,
    (icon) => `export {${icon.componentName}} from '${icon.fileName}';`,
  ).join('\n')}\n`;

  return `${warning}${exportSection}\n${deprecatedSection}`;
};

module.exports = {
  iconMarkdownTemplate,
  iconTemplate,
  iconIndexTemplate,
  pascalCase,
};
