#!/usr/bin/env python3
"""
ELM Manager Change Detection - Setup Wizard
Interactive configuration setup for new deployments
"""

import os
import sys
from pathlib import Path

def print_header(text):
    """Print a formatted header"""
    print("\n" + "="*70)
    print(text)
    print("="*70 + "\n")

def get_input(prompt, default=None):
    """Get user input with optional default"""
    if default:
        full_prompt = f"{prompt} [{default}]: "
    else:
        full_prompt = f"{prompt}: "
    
    value = input(full_prompt).strip()
    return value if value else default

def yes_no(prompt, default=True):
    """Get yes/no input"""
    default_str = "Y/n" if default else "y/N"
    response = input(f"{prompt} [{default_str}]: ").strip().lower()
    
    if not response:
        return default
    return response in ['y', 'yes']

def main():
    print_header("ELM MANAGER CHANGE DETECTION - SETUP WIZARD")
    
    print("This wizard will help you configure the system for your environment.")
    print("You can press CTRL+C at any time to cancel.\n")
    
    input("Press ENTER to begin...")
    
    # Step 1: User Information
    print_header("STEP 1: User Information")
    
    user_email = get_input(
        "Your Walmart email address",
        os.environ.get('USERNAME', '') + "@homeoffice.wal-mart.com"
    )
    
    user_name = get_input(
        "Your name (for notifications)",
        os.environ.get('USERNAME', 'Admin')
    )
    
    # Step 2: Shared Mailbox Configuration
    print_header("STEP 2: Shared Mailbox Configuration")
    
    print("This system sends emails from a shared mailbox.")
    print("You need 'Send As' permissions for the shared mailbox.\n")
    
    shared_mailbox = get_input(
        "Shared mailbox email address",
        "supplychainops@email.wal-mart.com"
    )
    
    shared_mailbox_name = get_input(
        "Shared mailbox display name",
        "Supply Chain Integration Operations"
    )
    
    print("\nIMPORTANT: Make sure you have added this shared mailbox to Outlook:")
    print("  1. Open Outlook")
    print("  2. File -> Account Settings -> Account Settings")
    print("  3. Select your account -> Change -> More Settings -> Advanced")
    print(f"  4. Add: {shared_mailbox}")
    print()
    
    has_mailbox = yes_no("Have you added the shared mailbox to Outlook?", False)
    if not has_mailbox:
        print("\n[WARNING] Please add the shared mailbox to Outlook before continuing.")
        print("The system will not be able to send emails without it.\n")
        if not yes_no("Continue anyway?", False):
            print("\nSetup cancelled. Please add the shared mailbox and run this wizard again.")
            return 1
    
    # Step 3: Test Mode Configuration  
    print_header("STEP 3: Test Mode Configuration")
    
    print("Test mode sends ALL emails to you instead of production distribution lists.")
    print("This is recommended for initial setup and testing.\n")
    
    test_mode = yes_no("Enable test mode?", True)
    
    if test_mode:
        print(f"\n[OK] Test mode enabled. All emails will go to: {user_email}")
    else:
        print("\n[WARNING] Test mode disabled. Emails will go to production DCs.")
        if not yes_no("Are you sure?", False):
            test_mode = True
            print("[OK] Test mode re-enabled for safety.")
    
    # Step 4: Location Filters
    print_header("STEP 4: Location Filters")
    
    print("By default, the system tracks:")
    print("  - Walmart Supercenters, Neighborhood Markets, Discount Stores")
    print("  - Sam's Club locations")
    print("  - ~5,200 total locations")
    print()
    
    use_filters = yes_no("Use default location filters?", True)
    
    # Step 5: VPN Retry Configuration
    print_header("STEP 5: VPN Retry Configuration")
    
    print("The system can retry for up to 7 days if VPN is unavailable.")
    print("Task Scheduler will run hourly and keep trying.\n")
    
    vpn_retry_days = int(get_input("Maximum retry days", "7"))
    
    # Step 6: Task Scheduler
    print_header("STEP 6: Task Scheduler Configuration")
    
    print("The system uses Windows Task Scheduler to run automatically.")
    print("Recommended: Run hourly starting at 2:00 AM\n")
    
    start_time = get_input("Start time (HH:MM format)", "02:00")
    
    setup_task = yes_no("Set up Task Scheduler now?", True)
    
    # Generate configuration files
    print_header("GENERATING CONFIGURATION FILES")
    
    print("Creating config.py...")
    
    config_content = f'''#!/usr/bin/env python3
"""
Configuration file for Manager Change Detection System.
Generated by Setup Wizard.
"""

from pathlib import Path

# OneDrive configuration
ONEDRIVE_FOLDER = "ManagerSnapshots"
SNAPSHOT_FILENAME_PATTERN = "manager_snapshot_{{date}}.json"

# Roles to track
ROLES_TO_TRACK = [
    "Store Manager",
    "Club Manager",
    "Market Manager",
    "Regional General Manager",
    "DC General Manager",
    "DC Assistant General Manager"
]

# SDL (Store Directory Lookup) configuration
SDL_URL = "https://elmsearchui.prod.elm-ui.telocmdm.prod.walmart.com/"
SDL_SEARCH_TIMEOUT = 30

# Email notification configuration
EMAIL_ENABLED = True
EMAIL_METHOD = "OUTLOOK_COM"

# Test mode - send all emails to this address
TEST_MODE = {test_mode}
TEST_EMAIL = "{user_email}"

# Shared mailbox configuration
SHARED_MAILBOX_EMAIL = "{shared_mailbox}"
SHARED_MAILBOX_NAME = "{shared_mailbox_name}"

# Distribution lists (used when TEST_MODE = False)
EMAIL_DISTRIBUTION = {{
    "Store Manager": ["{user_email}"],
    "Club Manager": ["{user_email}"],
    "Market Manager": ["{user_email}"],
    "Regional General Manager": ["{user_email}"],
    "DC General Manager": ["{user_email}"],
    "DC Assistant General Manager": ["{user_email}"]
}}

# Location Filters
FILTER_ENABLED = {use_filters}
EXCLUDE_OPERATING_STATUS_CODES = [7, 8]
INCLUDE_BASE_DIVISIONS = ["WAL-MART STORES INC.", "SAM'S CLUB"]
INCLUDE_BANNERS = ["WM Supercenter", "Neighborhood Market", "Wal-Mart", "Sam's Club"]
EXPECTED_LOCATION_COUNT = 5207

# VPN Retry Configuration
VPN_RETRY_ENABLED = True
VPN_MAX_RETRY_DAYS = {vpn_retry_days}
VPN_RETRY_INTERVAL_HOURS = 1
'''
    
    with open('config.py', 'w') as f:
        f.write(config_content)
    
    print("[OK] config.py created")
    
    # Summary
    print_header("SETUP COMPLETE!")
    
    print("Configuration Summary:")
    print(f"  User Email: {user_email}")
    print(f"  Shared Mailbox: {shared_mailbox}")
    print(f"  Test Mode: {'ENABLED' if test_mode else 'DISABLED'}")
    print(f"  VPN Retry: Up to {vpn_retry_days} days")
    print(f"  Location Filters: {'ENABLED' if use_filters else 'DISABLED'}")
    print()
    
    print("Next Steps:")
    print("  1. Review config.py and customize if needed")
    print("  2. Add shared mailbox to Outlook (if not done)")
    print("  3. Run: setup_hourly_task_auto.bat (as administrator)")
    print("  4. Test: python vpn_checker.py")
    print("  5. Test: python create_snapshot.py")
    print()
    print("See DEPLOYMENT_GUIDE.md for detailed instructions.")
    print()
    
    return 0

if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\nERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
