@echo off
REM ==========================================
REM Auto-Generate Weekly Audio — End-of-Day Check
REM ==========================================
REM Runs: Fridays at 5:00 PM
REM If audio was not generated by hourly checks, sends alert email
REM ==========================================

setlocal enabledelayedexpansion

set ProjectRoot=C:\Users\krush\OneDrive - Walmart Inc\Documents\VSCode\Activity_Hub
set AudioScripts=%ProjectRoot%\Store Support\Projects\AMP\Zorro\Audio\Scripts
set PythonExe=%ProjectRoot%\.venv\Scripts\python.exe
set LogFile=%AudioScripts%\auto_generate_weekly_audio.log

set GOOGLE_APPLICATION_CREDENTIALS=C:\Users\krush\AppData\Roaming\gcloud\application_default_credentials.json

echo [%date% %time%] ====== EOD Alert Check Starting ====== >> "%LogFile%"

cd /d "%AudioScripts%"

"%PythonExe%" auto_generate_weekly_audio.py --eod-check >> "%LogFile%" 2>&1

echo [%date% %time%] ====== EOD Alert Check Complete ====== >> "%LogFile%"
echo. >> "%LogFile%"
